### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by notramo** [catinello/ace-util#2]
Please create a tagged release.
It is a requirement for packaging in Void Linux (https://github.com/void-linux/void-packages/issues/12060).

**Comment by catinello** [comment]
I do not like the concept of versioning with major/minor numbers for small projects or any releases at that with arbitrary numbers.

I'd love to support your effort though and am a user of Void Linux myself. I just tagged the latest commit with it's date (YYMMDD). See [v160221](https://github.com/catinello/ace-util/releases/tag/v160221)

Thank you.
